services:
  app:
    image: ghcr.io/brandenespinoza/recipe.md:latest
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    volumes:
      - ./recipes:/recipes
      - ./data:/data
    ports:
      - "8000:8000"
